### ISSUE TITLE
Self overwriting getters

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#148]
Considering the N3 terms are immutable, how about making the getters self-overwriting?
I.e., change this:
```
Object.defineProperty(Literal.prototype, 'language', {
  get: function () {
    // Find the last quotation mark (e.g., '"abc"@en-us')
    var id = this.id, atPos = id.lastIndexOf('"') + 1;
    // If "@" it follows, return the remaining substring; empty otherwise
    return atPos < id.length && id[atPos++] === '@' ? id.substr(atPos).toLowerCase() : '';
  },
});
```
To this:
```
Object.defineProperty(Literal.prototype, 'language', {
  get: function () {
    // Find the last quotation mark (e.g., '"abc"@en-us')
    var id = this.id, atPos = id.lastIndexOf('"') + 1;
    // If "@" it follows, return the remaining substring; empty otherwise
    const lang = atPos < id.length && id[atPos++] === '@' ? id.substr(atPos).toLowerCase() : '';
    Object.defineProperty(this, "language", { value: lang, writable: false, configurable: true })
    return lang;
  },
});
```
This is a small optimization, but considering it comes at very little cost, it could be worth it

**Comment by rubensworks** [comment]
On the other hand, this will slightly increase memory usage, as redundant data will be stored.

I would say it definitely makes sense if these getters are called multiple times, but I'm not sure if this is a typical case.

Perhaps this optimization could be part of another variant of N3's DataFactory? Which may be used when the user is expected to call these getters often?

**Comment by RubenVerborgh** [comment]
I'm not sure it's an optimization. You lose honomorphism, might make V8 slower. We need a benchmark.

**Comment by LaurensRietveld** [comment]
Considering this is a small optimization, not worth the effort from my side to write a benchmark for it. Closing, but feel free to re-open if others want to persue this

**Comment by RubenVerborgh** [comment]
> Considering this is a small optimization, not worth the effort from my side to write a benchmark for it.

Yeah, I certainly did not mean to block this, it's a valid point. But the whole of V8 relies so strongly on homogeneous shapes, that my expectation is for this to be significantly slower instead of slightly faster.

I follow @rubensworks' argument about using different data factories for this purpose. N3.js' built-in factory relies on the assumption that individual properties will not be read _too_ often, such that the memory gain from using one string instead of three is justified.

But perhaps all of these assumptions should be tested, and we can easily do that thanks to the factory pattern. A benchmark could simply be to run some Comunica queries and see what happens.
