### ISSUE TITLE
ntriples serialization: canonical output

### ISSUE THREAD

**Issue by bjdmeest** [rdfjs/N3.js#153]
The spec encourages implementers to follow the canonical form: https://www.w3.org/TR/n-triples/#canonical-ntriples

current N3 is almost perfect, except for the 'not having a space before the `.`', and other issues have been raised on this eg #119 and #49

Is it possible for N3 to conform to the canonical form?

**Comment by RubenVerborgh** [comment]
Seems like there are more requirements though, that might require more processing:
- HEX MUST use only uppercase letters 
- Characters MUST NOT be represented by UCHAR

How strict are your requirements?

**Comment by jimsmart** [comment]
FWIW, the only time HEX is used in N-Triples grammar is in UCHAR. So that's easy enough to fix.

Furthermore, my understanding is that UCHAR is primarily a legacy feature: N-Triples was originally based upon 7-bit ASCII, so UCHAR was the only way to embed Unicode chars outside of that range into the stream. 

e.g. https://www.w3.org/2001/sw/RDFCore/ntriples/

But nowadays N-Triples is UTF-8, so there shouldn't be a need to use UCHAR in a writer, AFAICT.
