### ISSUE TITLE
Export ESM as well

### ISSUE THREAD

**Issue by CxRes** [rdfjs/N3.js#196]
There are two scenarios in which I am using this library - testing from the command line and bundling it:
+ For command line, it loads from `main`  property in package.json which reads the cjs version and I am required to use default import (because of how NodeJS interprets module.exports). NodeJS requires a `type` and `exports` property to be specified for dual use scenarios. See here: https://nodejs.org/api/esm.html
+ However, when I bundle, I have to make a named import because the bundler looks at the `module` property in package.json and reads the esm version of the library - which provides named export only.

Please fix this inconsistent behaviour. Temporarily, it can be fixed by adding a default export without affecting any users.

**Comment by RubenVerborgh** [comment]
> Temporarily, it can be fixed by adding a default export without affecting any users.

That's a good one.

Could also be fixed by https://nodejs.org/api/esm.html#esm_conditional_exports

**Comment by RubenVerborgh** [comment]
But actually, I'd be afraid that the default export might confuse some packers. Could you have a stab at https://nodejs.org/api/esm.html#esm_conditional_exports ?

**Comment by CxRes** [comment]
I tried to fix it by:
1. Adding `.js` extension to all local imports.
1. Adding the following to `package.json`
```json
  "type": "module",
  "exports": {
    "require": "./lib/index.js",
    "import": "./src/index.js"
  },
```


I am able to build successfully. However, the tests fail completely with an error like:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: N3.js\test\test-setup.js
require() of ES modules is not supported.
require() of N3.js\test\test-setup.js from N3.js\node_modules\mocha\bin\_mocha 
``` 
Also, there are a number of funky folder imports in tests which are certainly not to ESM spec. Bottom line, I am not sure how to get mocha running with tests in the current form...

**Comment by RubenVerborgh** [comment]
Okay, thanks for investigating. Let's see what we can do.

I really dislike Node's translation, has given me trouble elsewhere too.

**Comment by Vinnl** [comment]
I spent some time on this today, and I think I have a relatively clear picture on this now. Writing this down here because I'll probably have forgotten all the weird module intricacies by tomorrow.

Basically, n3 is currently written using ES imports/exports, but it's still a CommonJS module. Specifically, it does not have `"type": "module"` in the `package.json`. This means that if you import n3 from an ES module in Node, Node will collapse all the named exports into a single object as a default export. In other words, if you try to import from an ES module in Node (i.e. a file with an `.mjs` extension, or a `.js` file in a package with `"type": "module"` in its `package.json`), you can do `import n3 from "n3"`, but not `import { Parser } from "n3"`.

This would be fine, _except_ that there isn't actually a default export, meaning that you can't do `import n3 from "n3"` in e.g. Webpack. This is problematic for packages depending on n3 that want to work both in the browser as in Node (which is why I'm running into this).

Now, there are a couple of possible resolutions:

# 1. Tell ES Modules using Node to import the compiled code

This would be easiest. It does mean that, from the point of view of an ES module running in Node, n3 only provides a default export - i.e. named imports would not be possible.

In fact, this fix was so easy, I created a PR for your consideration: #231

# 2. Ditch CommonJS

Alternatively, you could add `"type": "module"` to the `package.json`. Major disadvantage here is that anyone writing non-ES module code in Node (i.e. not an `.mjs` file or no `"type": "module"`) would no longer be able to import from n3. Thus, seems like a no-go.

# 3. Add another build script to produce `.mjs` files

This would keep the source `.js` files available for bundlers not supporting `.mjs`, would keep the built `.js` files from `/lib` available for those using CommonJS, and you could direct those using ES modules in Node to the `.mjs` files using the exports map. Would inflate package size, and makes it possible that projects instantiate two different instances of the same class if they have different packages depending on n3, some using CommonJS and some using ES modules.

# 4. Switch to `require` statements and add wrapper modules

This would allow CommonJS projects to import the regular `.js` source files and ES module Node projects to import the `.mjs` files that re-export the CommonJS modules. Bundlers that do not understand `.mjs` would now encounter CommonJS modules though, breaking their ability to do tree-shaking. This would mainly be useful if you want developers to import from submodules (e.g. `import Lexer from "n3/lexer"`).

**Comment by RubenVerborgh** [comment]
> Basically, n3 is currently written using ES imports/exports, but it's still a CommonJS module. Specifically, it does not have `"type": "module"` in the `package.json`.

Indeed. I made the switch with https://github.com/RubenVerborgh/AsyncIterator/ a couple of months ago, and noticed that support was still shaky. But things evolve quickly, so maybe the situation is better now.

**Comment by Vinnl** [comment]
Yeah, I don't think it will be feasible for the foreseeable future to switch to actually being an ES module (i.e. option 2) fully. Option 3 (shipping both an ES module and a CommonJS module) seems feasible but, as you mentioned in #231, would require careful testing. Until then, a safe approach that would satisfy all situations would be #232.

**Comment by RubenVerborgh** [comment]
See https://github.com/rdfjs/N3.js/pull/233#issuecomment-863275752

**Comment by ThisIsMissEm** [comment]
Hey @RubenVerborgh, would you like me to have a go at switching this package to rollup? It's what we use for packaging all the Inrupt libraries, and supports output in various module types (commonjs, AMD, ESM, etc) — https://rollupjs.org/guide/en/

This would make the package tarball larger, but not the actual delivered code (if you're compiling it), though I wouldn't really suggest worrying about package size, as the package uncompressed is only 457kb, so increasing that by even three times isn't likely to make most blink (not compared to other libraries or frameworks).

**Comment by RubenVerborgh** [comment]
HI @ThisIsMissEm, thanks for proposing.

However, (and this might just be my understanding), I'm not sure if rollup is the right tool here? I thought rollup was a bundler, for usage in end-user apps that have N3.js as a dependency. Isn't a transpiler what we need here? I think we'd need cjs and esm versions.

Size on npm would indeed not be an issue.

**Comment by ThisIsMissEm** [comment]
@RubenVerborgh it is a bundler, but that's actually what you want in the case of libraries: you want to ship a few different versions of source code in your package for different targets. A transpiler would be what an end-user application would use to support different runtimes (browsers, node.js, deno, etc).

For N3, we need to take the source, and emit out code that is either cjs or esm, and that's what rollup can take care of (it can also transpile to different targets too)

**Comment by RubenVerborgh** [comment]
> emit out code that is either cjs or esm

We already have both in the published version on npm; it just seems that there is a misconfiguration at the moment.

> Please fix this inconsistent behaviour. Temporarily, it can be fixed by adding a default export without affecting any users.

I will already apply this one to at least fix the necessity of this hack https://github.com/inrupt/solid-client-js/commit/d43d1a6b360b14f4e229056923de10dcb37af996.

Happy to refine further.

**Comment by Vinnl** [comment]
To make it easier to apply that one fix, note that that was what https://github.com/rdfjs/N3.js/pull/233 did :)

**Comment by RubenVerborgh** [comment]
@Vinnl You're absolutely right; merging that one!

**Comment by RubenVerborgh** [comment]
Also switching Node.js export to module in https://github.com/rdfjs/N3.js/pull/270
