### ISSUE TITLE
N3 Writer fills up memory if addQuads() is called many times in rapid succession

### ISSUE THREAD

**Issue by belvederef** [rdfjs/N3.js#219]
As the title describes, if the N3.Writer `addQuads()` method is called many times in succession, the writer does not have time to write to the stream. This fills up memory linearly and continues until it causes an out of memory crash if enough ram is not available.

Here is the code used: 
```js
const fileWriteStream = fs.createWriteStream("./output.n3");
const writer = new N3.Writer(fileWriteStream, {
  end: false,
  format: "N-Triples",
});

for (let i = 0; i < 1000000; i++) {
  const quads = createQuads(); // example method creating an array of N3 quads
  writer.addQuads(quads);
}
```

To solve the problem, I added the following line in my for loop:
```js
  if (i % 5000 === 0) await new Promise((r) => setTimeout(r, 0));
```
This allows the event loop to process the write-to-stream task, and memory use stays low.

**Comment by RubenVerborgh** [comment]
That's not intended indeed, and should be looked into.

On the other hand, if you're writing a stream, I strongly suggest using `StreamWriter`.

**Comment by RubenVerborgh** [comment]
Upon closer investigation, this is a Node.js limitation. Since the `addQuads` is synchronous, and so is your loop, you are indeed not allowing Node.js (not N3.js) to write to disk. The solution is to use streams, as in my suggestion (and to deal with [backpressure](https://nodejs.org/es/docs/guides/backpressuring-in-streams/), which is what you are experiencing). Please reopen the PR should this not work.
