### ISSUE TITLE
FILTER on langString literals does not work

### ISSUE THREAD

**Issue by gvanderh** [rdfjs/N3.js#321]
```
// add a quad with a language string
const store = new N3.Store();
store.addQuad(namedNode('http://ex.com/s'), namedNode('http://ex.com/p'), literal('abc', 'en'));

// query it using SPARQL with a FILTER
const eng = new comunica.QueryEngine();
const bindings = await eng.queryBindings('SELECT ?o WHERE { ?s ?p ?o. FILTER(?o = "abc"@en) }', { sources: [ store ] });
```

Any FILTER on ?o in the example fails (with or without language string, = or !=).

**Comment by jeswr** [comment]
This looks like an issue with Comunica rather than N3.js so I suggest you open this issue [over there](https://github.com/comunica/comunica/issues).

When you do so could you please also elaborate on how it fails (does it miss results, include unexpected results, or does it crash - and if so what is the log when it crashes).

// cc @rubensworks

**Comment by gvanderh** [comment]
Thanks for your response. Forwarded to https://github.com/comunica/comunica/issues/1146.
